### ISSUE TITLE
Add Videos to TBA

### ISSUE THREAD

**Issue by phil-lopreiato** [tytremblay/FRC-Video-Splitter-2#1]
It would be awesome if videos split with the tool can be automatically added to TBA. There are actually two ways to approach doing this.
## Approach 1 - Trusted API

This approaches uses a trusted API that allows direct write access to TBA (no moderation queue required). As such, it requires keys generated by the admins, one for each event you wish to modify videos for. Documentation about request formats can be found [here](https://docs.google.com/document/d/1VFPgWKpKuUztE9WLjba9tUELC0T_U-eH7qyCrMrg4wo)
## Approach 2 - Suggestions

This approach is not fully implemented yet, but will be easy to do. It would use the same endpoint behind Robot image suggestions done via the Android app. All you need is a Google oauth token, and you could submit videos into the moderation queue for review. Since this isn't implemented yet, we can determine a format here. The only thing is, it will require authentication against [Google Cloud Endpoints](https://cloud.google.com/endpoints/), which should only require a Google oauth token ([here's how I generate it in the Android app](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/datafeed/gce/GceAuthController.java#L68), for reference)

**Comment by alexherreid** [comment]
#7 would resolve this by adding option to put TBA trusted info in "output options" when running the program

**Comment by tytremblay** [comment]
Merged #7.
