### ISSUE TITLE
Arkansas Rock City Regional Returns Error 

### ISSUE THREAD

**Issue by maxnz** [tytremblay/FRC-Video-Splitter-2#5]
When I try to get the data for the Rock City Regional, an exception occurs: Object reference not set to an instance of an object.

This may be because the event code for the Arkansas Rock City Regional is ARLI this year, not ARLR as it was last year and how the program has it saved as. I tried changing the event code in the box but that didn't make a difference.

Maybe there needs to be a way to get the data from the code and name entered by a user.

**Comment by tytremblay** [comment]
Hi @maxnz.  To fix this, go to Edit -> Settings, then change the year to 2017 and click "Update FRC Data".

It should pull the right data after that.

**Comment by maxnz** [comment]
That worked. Thanks!
